name: Deploy documentation website

on: [push, pull_request, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme myst_parser
    - name: Build documentation
      run: |
        sphinx-build docs build
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/sphinx/html/
      if: github.event_name == 'push'